name: Install development tools
description: GitHub Action for installing development tools

inputs:
  tool:
    description: Tools to install (comma-separated list)
    required: false
    default: wasm-pack

runs:
  using: node16
  main: main.js
